<!-- Footer displayed at bottom of every file comes here -->

<footer>
<p><small>Generated by <a href="https://github.com/sanand0/markdress">Markdress</a>:
a static Markdown site generator.</small></p>
</footer>
