<!-- Footer displayed at bottom of every file comes here -->

<footer>
<p><small>Generated by <a href="http://markdress.org/">markdress.org</a>:
a static Markdown site generator.</small></p>
</footer>
